export const venue = [
    {
        img:"assets/img/venue-gallery/1.jpg"
    },
    {
        img:"assets/img/venue-gallery/2.jpg"
    },
    {
        img:"assets/img/venue-gallery/3.jpg"
    },
    {
        img:"assets/img/venue-gallery/4.jpg"
    },
    {
        img:"assets/img/venue-gallery/5.jpg"
    },
    {
        img:"assets/img/venue-gallery/6.jpg"
    },
    {
        img:"assets/img/venue-gallery/7.jpg"
    },
    {
        img:"assets/img/venue-gallery/8.jpg"
    }
]